pipeline {
	agent any
	stages {

		stage('Create kubernetes cluster') {
			steps {
				withAWS(region:'eu-central-1', credentials:'eks_credentials') {
					sh '''
						eksctl create cluster \
						--name capstone_cluster \
						--nodegroup-name standard-workers \
						--node-type t2.small \
						--nodes 3 \
						--region eu-central-1 \
						--zones eu-central-1a \
						--zones eu-central-1b \
						--zones eu-central-1c \
					'''
				}
			}
		}



		stage('Create conf file cluster') {
			steps {
				withAWS(region:'eu-central-1', credentials:'eks_credentials') {
					sh '''
						aws eks --region eu-central-1 update-kubeconfig --name capstone_cluster
					'''
				}
			}
		}

	}
}